services:
  app:
    build: .
    container_name: homelab-dashboard
    networks:
      - proxy-network
    ports:
      - "8100:8100"
    restart: unless-stopped 

networks:
  proxy-network:
    external: true
